platform/x86/intel/ifs: Add CPU_SUP_INTEL dependency
commit badb81a58b9e66ca8c15405476f5134e45b57dee upstream.

The driver is using functions from a compilation unit which is enabled
by CONFIG_CPU_SUP_INTEL. Add that dependency to Kconfig explicitly
otherwise:

  drivers/platform/x86/intel/ifs/load.o: in function `ifs_load_firmware':
  load.c:(.text+0x3b8): undefined reference to `intel_cpu_collect_info'

Intel-SIG: commit badb81a58b9e platform/x86/intel/ifs: Add CPU_SUP_INTEL
dependency.
Backport for Intel IFS (In Field Scan) support.

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Borislav Petkov <bp@suse.de>
Link: https://lore.kernel.org/r/YoZay8YR0zRGyVu+@zn.tnic
Signed-off-by: Hans de Goede <hdegoede@redhat.com>
[ Jing Han: amend commit log ]
Signed-off-by: Jing Han <jing1.han@intel.com>
Signed-off-by: Yunhui Cui <cuiyunhui@bytedance.com>